on: [push, pull_request]
name: every commit
jobs:

  build:
    runs-on: ubuntu-latest
    name: build
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - run: go build ./...
       - uses: actions/upload-artifact@v2


  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: go test ./...
