on: [push, pull_request]
name: every commit
jobs:



# Yeah, this makes releases that run in  a single click and serve on port 3000 for windows, mac and linux. 
  build:
    runs-on: ubuntu-latest
    name: build
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - run: |
          cd cmd/cookiemonster
          go build .
      - uses: actions/upload-artifact@v2
        with:
          path: cmd/cookiemonster/cookiemonster
      


  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: go test ./...

  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest

  frontend:
    name: javascript
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '17'
    - run: |
        cd frontend
        yarn install
        yarn run build
        
        


    
